import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Footer from '../components/UI/Footer/Footer'
import TopNav from '../components/UI/TopNav/TopNav'
import styles from '../styles/pages/ClientList.module.scss'

function index() {
  return (
    <div className={styles.container}>
    <Head>
      <title>SiteSec Dashboard</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <TopNav />

    <Footer />
  </div>
  )
}

export default index
